{{- if .Values.k3s.enabled }}
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  labels:
    k3s-upgrade: server
  name: k3s-server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: k3os.io/mode
        operator: DoesNotExist
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: {{ .Values.k3s.version }}
{{- end }}