name: 'Terraform destroy'

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
concurrency:
  group: ${{ github.workflow }}-${{ inputs.env }}
  cancel-in-progress: false
jobs:
  terraform_destroy:
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    uses: mars-office/.github/.github/workflows/terraform_destroy.yaml@main
    with:
      env: ${{ inputs.env }}
    secrets: inherit