name: 'Terraform DEV'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'dev/**'
      - 'modules/**'
      - '.github/workflows/dev.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'dev/**'
      - 'modules/**'
      - '.github/workflows/dev.yaml'

jobs:
  terraform:
    permissions:
      pull-requests: write
    uses: mars-office/.github/.github/workflows/terraform.yaml@main
    with:
      env: dev
    secrets: inherit
  snyk_iac_terraform:
    uses: mars-office/.github/.github/workflows/snyk_iac_terraform.yaml@main
    with:
      folder: dev
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    secrets: inherit
    needs: []
  snyk_iac_tfplan:
    uses: mars-office/.github/.github/workflows/snyk_iac_tfplan.yaml@main
    with:
      folder: dev
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    secrets: inherit
    needs: [terraform]