name: 'Terraform DEV'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'dev/**'
      - 'modules/**'
      - '.github/workflows/dev.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'dev/**'
      - 'modules/**'
      - '.github/workflows/dev.yaml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  terraform:
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    uses: mars-office/.github/.github/workflows/terraform.yaml@main
    with:
      env: dev
    secrets: inherit