name: 'Download Kubeconfig'

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment

jobs:
  terraform_destroy:
    uses: mars-office/.github/.github/workflows/download_kubeconfig.yaml@main
    with:
      env: ${{ inputs.env }}
    secrets: inherit