name: 'Download kubeconfig'

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: dev
        description: Environment
        options: 
          - dev
          - uat
          - prod

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Output secret to temp file
        run: echo '${{ secrets[format('{0}_KUBECONFIG', inputs.env)] }}' > /tmp/kubeconfig_${{ inputs.env }}.yaml

      - name: Upload kubeconfig to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.env }}_kubeconfig
          path: /tmp/kubeconfig_${{ inputs.env }}.yaml