name: 'Terraform PROD'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'prod/**'
      - 'modules/**'
      - '.github/workflows/prod.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'prod/**'
      - 'modules/**'
      - '.github/workflows/prod.yaml'

jobs:
  terraform:
    permissions:
      pull-requests: write
    uses: mars-office/.github/.github/workflows/terraform.yaml@main
    with:
      env: prod
      appName: huna