name: 'Terraform PROD'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'prod/**'
      - 'modules/**'
      - '.github/workflows/prod.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'prod/**'
      - 'modules/**'
      - '.github/workflows/prod.yaml'

jobs:
  terraform_plan:
    uses: mars-office/.github/.github/workflows/terraform_plan.yaml@main
    with:
      env: prod
    secrets:
      terraformToken: ${{ secrets.TERRAFORM_TEAM_TOKEN }}