name: 'Snyk'

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  snyk:
    uses: mars-office/.github/.github/workflows/snyk.yaml@main
    permissions:
      actions: read
      contents: read
      security-events: write
    secrets: inherit
    with:
      scanType: 'iac'
