name: 'Terraform UAT'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'uat/**'
      - 'modules/**'
      - '.github/workflows/uat.yaml'

  pull_request:
    branches:
      - main
    paths:
      - 'uat/**'
      - 'modules/**'
      - '.github/workflows/uat.yaml'

jobs:
  terraform:
    permissions:
      pull-requests: write
    uses: mars-office/.github/.github/workflows/terraform.yaml@main
    with:
      env: uat
    secrets: inherit
  snyk_iac_terraform:
    uses: mars-office/.github/.github/workflows/snyk_iac_terraform.yaml@main
      with:
        folder: uat
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    secrets: inherit
    needs: []